# SPDX-License-Identifier: MIT
spring.profiles.include:
- pds_localserver

# next lines is a default when running inside IDE. Links to sechub-integration aprts
sechub.pds.config.file: "src/test/resources/dev-pds-config.json"

sechub:
 pds:
   techuser:
       userid: pds-inttest-techuser
       apitoken: pds-inttest-apitoken

logging:
 level:
   com.daimler.sechub: DEBUG
   org.apache.http: WARN
   org.apache.http.headers: WARN
   org.apache.http.wire: WARN
